import { DataHealthStatus, Game, Insight, Sport, Team, TeamProfile, WatchlistItem } from "@/lib/types";

export const sports: Sport[] = [
  { key: "NBA", name: "NBA", season: "2025-26", accent: "#58c7ff" },
  { key: "MLB", name: "MLB", season: "2026", accent: "#9fffaf" },
  { key: "NFL", name: "NFL", season: "2026", accent: "#ff8e65" },
  { key: "NCAAB", name: "NCAA Men's Basketball", season: "2025-26", accent: "#b8ff3b" },
  { key: "NHL", name: "NHL", season: "2025-26", accent: "#d8dee9" },
];

export const teams: Team[] = [
  { id: "bos-celtics", sport: "NBA", city: "Boston", name: "Celtics", code: "BOS", shortName: "Celtics", logoUrl: "https://a.espncdn.com/i/teamlogos/nba/500/bos.png", primaryColor: "#0f8a5f", secondaryColor: "#d7ba7d", rank: 2, record: "55-21", atsRecord: "41-33-2", ouRecord: "36-39-1" },
  { id: "den-nuggets", sport: "NBA", city: "Denver", name: "Nuggets", code: "DEN", shortName: "Nuggets", logoUrl: "https://a.espncdn.com/i/teamlogos/nba/500/den.png", primaryColor: "#2d6cdf", secondaryColor: "#f7c948", rank: 4, record: "52-24", atsRecord: "39-35-2", ouRecord: "38-36-2" },
  { id: "nyy-yankees", sport: "MLB", city: "New York", name: "Yankees", code: "NYY", shortName: "Yankees", logoUrl: "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png", primaryColor: "#173a63", secondaryColor: "#c4ced4", rank: 3, record: "7-3", atsRecord: "6-4", ouRecord: "4-6" },
  { id: "lad-dodgers", sport: "MLB", city: "Los Angeles", name: "Dodgers", code: "LAD", shortName: "Dodgers", logoUrl: "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png", primaryColor: "#0f4c81", secondaryColor: "#e1f1ff", rank: 1, record: "8-2", atsRecord: "7-3", ouRecord: "5-5" },
  { id: "bal-ravens", sport: "NFL", city: "Baltimore", name: "Ravens", code: "BAL", shortName: "Ravens", logoUrl: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png", primaryColor: "#2a004f", secondaryColor: "#f4bf3b", rank: 3, record: "13-4", atsRecord: "10-7", ouRecord: "8-9" },
  { id: "kc-chiefs", sport: "NFL", city: "Kansas City", name: "Chiefs", code: "KC", shortName: "Chiefs", logoUrl: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", primaryColor: "#c8102e", secondaryColor: "#ffb81c", rank: 1, record: "14-3", atsRecord: "8-9", ouRecord: "7-10" },
  { id: "duke-blue-devils", sport: "NCAAB", city: "Duke", name: "Blue Devils", code: "DUKE", shortName: "Duke", logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png", primaryColor: "#003087", secondaryColor: "#ffffff", rank: 4, record: "28-6", atsRecord: "19-14-1", ouRecord: "15-19" },
  { id: "unc-tar-heels", sport: "NCAAB", city: "North Carolina", name: "Tar Heels", code: "UNC", shortName: "UNC", logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png", primaryColor: "#7bafd4", secondaryColor: "#ffffff", rank: 8, record: "26-8", atsRecord: "17-16-1", ouRecord: "18-16" },
  { id: "nyr-rangers", sport: "NHL", city: "New York", name: "Rangers", code: "NYR", shortName: "Rangers", logoUrl: "https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png", primaryColor: "#0038a8", secondaryColor: "#ce1126", rank: 6, record: "45-25-5", atsRecord: "40-35", ouRecord: "33-39-3" },
  { id: "bos-bruins", sport: "NHL", city: "Boston", name: "Bruins", code: "BOS", shortName: "Bruins", logoUrl: "https://a.espncdn.com/i/teamlogos/nhl/500/bos.png", primaryColor: "#ffb81c", secondaryColor: "#000000", rank: 7, record: "43-24-8", atsRecord: "39-36", ouRecord: "34-37-4" },
];

export const games: Game[] = [
  {
    id: "nba-bos-den",
    sport: "NBA",
    league: "NBA",
    startTime: "2026-04-04T19:30:00-07:00",
    venue: "Ball Arena",
    awayTeamId: "bos-celtics",
    homeTeamId: "den-nuggets",
    headline: "Contender test with playoff seeding implications",
    importance: "Featured",
    popularityScore: 97,
    books: ["Pinnacle", "Circa", "DraftKings"],
    currentLine: {
      moneyline: { away: -118, home: +100 },
      spread: { away: -1.5, home: +1.5 },
      total: { points: 228.5, overPrice: -108, underPrice: -112 },
    },
    openingLine: {
      moneyline: { away: -105, home: -115 },
      spread: { away: +1.0, home: -1.0 },
      total: { points: 231.0, overPrice: -110, underPrice: -110 },
    },
    lineMovement: [
      { market: "moneyline", open: -105, current: -118, delta: -13, direction: "down", summary: "Market has moved toward Boston since open." },
      { market: "spread", open: 1, current: -1.5, delta: -2.5, direction: "down", summary: "Spread flipped through pick'em after early Denver injury concern." },
      { market: "total", open: 231, current: 228.5, delta: -2.5, direction: "down", summary: "Under money followed sharper overnight positions." },
    ],
    quickInsight: "Boston grades better in half-court defense and turnover creation; Denver's injury report softens interior depth.",
    marketSummary: "Two-way action early, but sharper buyback hit Boston and the under after open.",
    metrics: [
      { key: "off_eff", label: "Offensive Rating", awayValue: 120.4, homeValue: 118.8, higherIsBetter: true },
      { key: "def_eff", label: "Defensive Rating", awayValue: 111.3, homeValue: 113.7, higherIsBetter: false },
      { key: "pace", label: "Pace", awayValue: 98.5, homeValue: 97.1, higherIsBetter: true },
      { key: "efg", label: "eFG%", awayValue: 57.8, homeValue: 56.2, format: "percent", higherIsBetter: true },
      { key: "rebound", label: "Rebound Rate", awayValue: 51.8, homeValue: 50.4, format: "percent", higherIsBetter: true },
    ],
    trends: [
      { label: "Last 10", away: "8-2", home: "6-4" },
      { label: "Home/Away", away: "Road 24-13", home: "Home 29-9" },
      { label: "ATS", away: "5-2 last 7", home: "2-5 last 7" },
      { label: "Rest", away: "1 day", home: "0 days" },
    ],
    injuries: [
      { id: "inj-1", teamId: "den-nuggets", player: "Aaron Gordon", status: "Questionable", impact: "High", note: "Calf tightness; late decision." },
      { id: "inj-2", teamId: "bos-celtics", player: "Jrue Holiday", status: "Probable", impact: "Medium", note: "Expected to play through shoulder soreness." },
    ],
    projection: {
      gameId: "nba-bos-den",
      projectedHomeScore: 112,
      projectedAwayScore: 116,
      fairSpread: -3.2,
      fairTotal: 227.4,
      fairMoneylineHome: +135,
      modelEdgePercent: 4.7,
      confidence: "High",
      lean: "Celtics -1.5",
      rationale: [
        "Boston owns the stronger net rating split over the last 15 games.",
        "Denver loses rim pressure and switching versatility if Gordon sits.",
        "The market total is still slightly above the model after pace and fatigue adjustments.",
      ],
    },
    lineHistory: [
      { time: "9 AM", spread: 1, total: 231 },
      { time: "12 PM", spread: 0.5, total: 230.5 },
      { time: "3 PM", spread: -0.5, total: 229.5 },
      { time: "6 PM", spread: -1.5, total: 228.5 },
    ],
  },
  {
    id: "mlb-nyy-lad",
    sport: "MLB",
    league: "MLB",
    startTime: "2026-04-04T18:10:00-07:00",
    venue: "Dodger Stadium",
    awayTeamId: "nyy-yankees",
    homeTeamId: "lad-dodgers",
    headline: "Star-powered interleague matchup with ace-level pitching context",
    importance: "Featured",
    popularityScore: 95,
    books: ["Pinnacle", "FanDuel", "BetMGM"],
    currentLine: {
      moneyline: { away: +128, home: -142 },
      spread: { away: +1.5, home: -1.5 },
      total: { points: 8.0, overPrice: -102, underPrice: -118 },
    },
    openingLine: {
      moneyline: { away: +118, home: -130 },
      spread: { away: +1.5, home: -1.5 },
      total: { points: 8.5, overPrice: -110, underPrice: -110 },
    },
    lineMovement: [
      { market: "moneyline", open: +118, current: +128, delta: 10, direction: "up", summary: "Dodgers support increased through the day." },
      { market: "spread", open: 1.5, current: 1.5, delta: 0, direction: "flat", summary: "Run line held while juice shifted toward Los Angeles." },
      { market: "total", open: 8.5, current: 8, delta: -0.5, direction: "down", summary: "Under interest followed confirmed wind-in conditions." },
    ],
    quickInsight: "Weather and bullpen freshness push the total down; Yankees still offer some price if the lineup is fully healthy.",
    marketSummary: "The market respected the Dodgers bullpen edge and trimmed the total after weather updates.",
    weather: {
      summary: "Cool marine layer with mild wind blowing in from center.",
      temperature: 62,
      windMph: 9,
      precipitationChance: 4,
    },
    metrics: [
      { key: "wrc", label: "wRC+", awayValue: 121, homeValue: 128, higherIsBetter: true },
      { key: "ops", label: "OPS", awayValue: 0.802, homeValue: 0.836, format: "decimal", higherIsBetter: true },
      { key: "bullpen", label: "Bullpen ERA", awayValue: 3.88, homeValue: 2.94, higherIsBetter: false },
      { key: "k_rate", label: "Strikeout Rate", awayValue: 24.2, homeValue: 26.3, format: "percent", higherIsBetter: true },
      { key: "hard_hit", label: "Hard Hit%", awayValue: 41.7, homeValue: 43.2, format: "percent", higherIsBetter: true },
    ],
    trends: [
      { label: "Last 10", away: "7-3", home: "8-2" },
      { label: "Bullpen Usage", away: "8.2 IP last 2 days", home: "4.1 IP last 2 days" },
      { label: "Totals", away: "Under 6-4", home: "Under 5-5" },
      { label: "Split", away: "vs RHP .338 wOBA", home: "Home OPS .854" },
    ],
    injuries: [
      { id: "inj-3", teamId: "nyy-yankees", player: "Giancarlo Stanton", status: "Questionable", impact: "Medium", note: "Late lineup check due to hamstring tightness." },
    ],
    projection: {
      gameId: "mlb-nyy-lad",
      projectedHomeScore: 4.5,
      projectedAwayScore: 3.6,
      fairSpread: -1.1,
      fairTotal: 7.6,
      fairMoneylineHome: -151,
      modelEdgePercent: 2.8,
      confidence: "Moderate",
      lean: "Under 8.0",
      rationale: [
        "Both starting staffs profile for swing-and-miss against these lineups.",
        "Wind direction and park conditions mute carry.",
        "Dodgers bullpen freshness reduces late scoring expectation.",
      ],
    },
    lineHistory: [
      { time: "9 AM", spread: 1.5, total: 8.5 },
      { time: "12 PM", spread: 1.5, total: 8.5 },
      { time: "3 PM", spread: 1.5, total: 8.0 },
      { time: "6 PM", spread: 1.5, total: 8.0 },
    ],
  },
  {
    id: "nfl-bal-kc",
    sport: "NFL",
    league: "NFL",
    startTime: "2026-09-10T17:20:00-07:00",
    venue: "Arrowhead Stadium",
    awayTeamId: "bal-ravens",
    homeTeamId: "kc-chiefs",
    headline: "Early lookahead market with two elite AFC contenders",
    importance: "Strong",
    popularityScore: 88,
    books: ["Circa", "Pinnacle", "DraftKings"],
    currentLine: {
      moneyline: { away: +142, home: -162 },
      spread: { away: +3.5, home: -3.5 },
      total: { points: 48.5, overPrice: -110, underPrice: -110 },
    },
    openingLine: {
      moneyline: { away: +128, home: -148 },
      spread: { away: +3.0, home: -3.0 },
      total: { points: 49.5, overPrice: -110, underPrice: -110 },
    },
    lineMovement: [
      { market: "moneyline", open: +128, current: +142, delta: 14, direction: "up", summary: "Chiefs drew steady support in lookahead trading." },
      { market: "spread", open: 3, current: 3.5, delta: 0.5, direction: "up", summary: "A key move through 3 followed injury noise on Baltimore's OL." },
      { market: "total", open: 49.5, current: 48.5, delta: -1, direction: "down", summary: "Initial total came down with cooler weather assumptions." },
    ],
    quickInsight: "This matchup is useful as a template for NFL expansion: rest, explosive-play rate, and OL health are the current drivers.",
    marketSummary: "A future-facing NFL record is included to validate the multi-sport architecture.",
    weather: {
      summary: "Projected mild evening with moderate crosswind.",
      temperature: 71,
      windMph: 11,
      precipitationChance: 18,
    },
    metrics: [
      { key: "epa", label: "EPA / Play", awayValue: 0.14, homeValue: 0.17, format: "decimal", higherIsBetter: true },
      { key: "yards", label: "Yards / Play", awayValue: 6.3, homeValue: 6.5, higherIsBetter: true },
      { key: "redzone", label: "Red Zone TD%", awayValue: 62.1, homeValue: 66.8, format: "percent", higherIsBetter: true },
      { key: "sack", label: "Sack Rate Allowed", awayValue: 6.2, homeValue: 4.8, format: "percent", higherIsBetter: false },
    ],
    trends: [
      { label: "Last 10", away: "7-3", home: "8-2" },
      { label: "ATS", away: "6-4", home: "4-6" },
      { label: "Explosive Plays", away: "+14", home: "+19" },
      { label: "Rest", away: "Normal", home: "Normal" },
    ],
    injuries: [
      { id: "inj-4", teamId: "bal-ravens", player: "Starting LT", status: "Questionable", impact: "High", note: "Practice load limited after knee procedure." },
    ],
    projection: {
      gameId: "nfl-bal-kc",
      projectedHomeScore: 27,
      projectedAwayScore: 23,
      fairSpread: -4.1,
      fairTotal: 48.1,
      fairMoneylineHome: -176,
      modelEdgePercent: 1.9,
      confidence: "Low",
      lean: "Chiefs -3.5",
      rationale: [
        "Kansas City keeps the edge in explosive play creation and pass protection.",
        "The market may still be pricing Baltimore close to full health up front.",
      ],
    },
    lineHistory: [
      { time: "Open", spread: 3, total: 49.5 },
      { time: "1 PM", spread: 3, total: 49.0 },
      { time: "4 PM", spread: 3.5, total: 48.5 },
      { time: "Latest", spread: 3.5, total: 48.5 },
    ],
  },
  {
    id: "ncaab-duke-unc",
    sport: "NCAAB",
    league: "NCAAB",
    startTime: "2026-04-04T17:00:00-07:00",
    venue: "Madison Square Garden",
    awayTeamId: "duke-blue-devils",
    homeTeamId: "unc-tar-heels",
    headline: "Blue-blood rivalry with tournament seeding implications",
    importance: "Featured",
    popularityScore: 93,
    books: ["Pinnacle", "Circa", "DraftKings"],
    currentLine: {
      moneyline: { away: -142, home: +122 },
      spread: { away: -2.5, home: +2.5 },
      total: { points: 151.5, overPrice: -110, underPrice: -110 },
    },
    openingLine: {
      moneyline: { away: -130, home: +110 },
      spread: { away: -1.5, home: +1.5 },
      total: { points: 149.5, overPrice: -110, underPrice: -110 },
    },
    lineMovement: [
      { market: "moneyline", open: -130, current: -142, delta: -12, direction: "down", summary: "Early money backed Duke after the opener." },
      { market: "spread", open: -1.5, current: -2.5, delta: -1, direction: "down", summary: "The number ticked toward Duke with respected support." },
      { market: "total", open: 149.5, current: 151.5, delta: 2, direction: "up", summary: "Tempo expectations pushed the total higher." },
    ],
    quickInsight: "Duke's rim defense and turnover profile are strong, but UNC's pace and transition scoring keep the total live.",
    marketSummary: "Duke has drawn side support while the total has been bet upward on pace expectations.",
    metrics: [
      { key: "off_eff", label: "Offensive Efficiency", awayValue: 122.1, homeValue: 119.3, higherIsBetter: true },
      { key: "def_eff", label: "Defensive Efficiency", awayValue: 95.4, homeValue: 99.1, higherIsBetter: false },
      { key: "pace", label: "Pace", awayValue: 69.2, homeValue: 72.8, higherIsBetter: true },
      { key: "efg", label: "eFG%", awayValue: 56.8, homeValue: 54.9, format: "percent", higherIsBetter: true },
    ],
    trends: [
      { label: "Last 10", away: "8-2", home: "7-3" },
      { label: "ATS", away: "6-3-1", home: "5-5" },
      { label: "Rebound Rate", away: "52.4%", home: "50.8%" },
      { label: "Rest", away: "2 days", home: "2 days" },
    ],
    injuries: [
      { id: "inj-5", teamId: "unc-tar-heels", player: "Starting wing", status: "Questionable", impact: "Medium", note: "Ankle issue; warmups likely decide availability." },
    ],
    projection: {
      gameId: "ncaab-duke-unc",
      projectedHomeScore: 73,
      projectedAwayScore: 78,
      fairSpread: -3.8,
      fairTotal: 150.8,
      fairMoneylineHome: +148,
      modelEdgePercent: 3.5,
      confidence: "Moderate",
      lean: "Duke -2.5",
      rationale: [
        "Duke's defense grades better against UNC's primary shot zones.",
        "UNC can still force tempo, but Duke has the cleaner half-court profile.",
      ],
    },
    lineHistory: [
      { time: "Open", spread: -1.5, total: 149.5 },
      { time: "Noon", spread: -2.0, total: 150.5 },
      { time: "3 PM", spread: -2.5, total: 151.5 },
      { time: "Latest", spread: -2.5, total: 151.5 },
    ],
  },
  {
    id: "nhl-nyr-bos",
    sport: "NHL",
    league: "NHL",
    startTime: "2026-04-04T16:30:00-07:00",
    venue: "TD Garden",
    awayTeamId: "nyr-rangers",
    homeTeamId: "bos-bruins",
    headline: "Playoff-style Eastern matchup with goaltending emphasis",
    importance: "Strong",
    popularityScore: 84,
    books: ["Pinnacle", "FanDuel", "BetMGM"],
    currentLine: {
      moneyline: { away: +118, home: -132 },
      spread: { away: +1.5, home: -1.5 },
      total: { points: 5.5, overPrice: +102, underPrice: -122 },
    },
    openingLine: {
      moneyline: { away: +110, home: -125 },
      spread: { away: +1.5, home: -1.5 },
      total: { points: 6.0, overPrice: -110, underPrice: -110 },
    },
    lineMovement: [
      { market: "moneyline", open: +110, current: +118, delta: 8, direction: "up", summary: "Boston support came in after morning skate updates." },
      { market: "spread", open: 1.5, current: 1.5, delta: 0, direction: "flat", summary: "Puck line held steady while price shifted toward Boston." },
      { market: "total", open: 6, current: 5.5, delta: -0.5, direction: "down", summary: "Under money followed confirmed starting goalies." },
    ],
    quickInsight: "The total moved down on goaltending and expected five-on-five pace; Boston's home forecheck is the side driver.",
    marketSummary: "Goaltending confirmation shaped the total while Boston drew modest home support.",
    metrics: [
      { key: "xgf", label: "xGF%", awayValue: 53.4, homeValue: 54.8, format: "percent", higherIsBetter: true },
      { key: "pp", label: "Power Play%", awayValue: 24.8, homeValue: 26.1, format: "percent", higherIsBetter: true },
      { key: "pk", label: "Penalty Kill%", awayValue: 82.4, homeValue: 84.1, format: "percent", higherIsBetter: true },
      { key: "sv", label: "Save%", awayValue: 91.7, homeValue: 92.3, format: "percent", higherIsBetter: true },
    ],
    trends: [
      { label: "Last 10", away: "6-4", home: "7-3" },
      { label: "Home/Away", away: "Road 20-13-3", home: "Home 24-9-4" },
      { label: "Totals", away: "Under 6-4", home: "Under 7-3" },
      { label: "Rest", away: "0 days", home: "1 day" },
    ],
    injuries: [
      { id: "inj-6", teamId: "nyr-rangers", player: "Top-six winger", status: "Probable", impact: "Medium", note: "Expected to return after maintenance day." },
    ],
    projection: {
      gameId: "nhl-nyr-bos",
      projectedHomeScore: 3.1,
      projectedAwayScore: 2.4,
      fairSpread: -0.6,
      fairTotal: 5.3,
      fairMoneylineHome: -144,
      modelEdgePercent: 2.4,
      confidence: "Moderate",
      lean: "Under 5.5",
      rationale: [
        "Both teams suppress shots well at five-on-five.",
        "The rest edge favors Boston, but the bigger signal is low-event game state.",
      ],
    },
    lineHistory: [
      { time: "Open", spread: 1.5, total: 6.0 },
      { time: "Noon", spread: 1.5, total: 5.5 },
      { time: "3 PM", spread: 1.5, total: 5.5 },
      { time: "Latest", spread: 1.5, total: 5.5 },
    ],
  },
];

export const insights: Insight[] = [
  { id: "ins-1", title: "Boston's switchability has driven under tickets late in the day", category: "Market watch", summary: "The Celtics' recent defensive form and Denver's injury uncertainty moved both the side and total. The current number still leaves a slim under lean.", timestamp: "14 minutes ago" },
  { id: "ins-2", title: "Dodger Stadium weather is the cleanest signal on tonight's MLB board", category: "Matchup note", summary: "With wind blowing in and both bullpens rested, the total got bet down. The shape of the move is supported by context rather than pure steam.", timestamp: "31 minutes ago" },
  { id: "ins-3", title: "Model edges are strongest when market movement and injuries align", category: "Education", summary: "This MVP favors spots where recent form, lineup status, and line direction tell the same story, reducing false positives from raw power ratings alone.", timestamp: "Today" },
];

export const teamProfiles: TeamProfile[] = [
  {
    teamId: "bos-celtics",
    overview: "Elite two-way profile with top-tier half-court defense and deep rotation optionality.",
    strengths: ["Transition defense", "Turnover creation", "Shot quality balance"],
    concerns: ["Bench creation dips when primary ball handlers sit", "Can settle for perimeter volume"],
    metrics: [
      { label: "Net Rating", value: "+9.1", rank: 2 },
      { label: "3P Attempt Rate", value: "46.2%", rank: 1 },
      { label: "Defensive Rebound Rate", value: "74.1%", rank: 4 },
    ],
    upcoming: [
      { opponent: "at Phoenix", date: "Apr 6", location: "Away" },
      { opponent: "vs Miami", date: "Apr 8", location: "Home" },
    ],
  },
  {
    teamId: "lad-dodgers",
    overview: "Run creation depth and bullpen stability make Los Angeles one of the market's most consistently expensive teams.",
    strengths: ["Power through entire order", "Bullpen leverage arms", "Hard-hit quality"],
    concerns: ["Price inflation in marquee games", "Occasional platoon vulnerability"],
    metrics: [
      { label: "wRC+", value: "128", rank: 1 },
      { label: "Bullpen ERA", value: "2.94", rank: 2 },
      { label: "BB Rate", value: "10.8%", rank: 3 },
    ],
    upcoming: [
      { opponent: "vs Yankees", date: "Apr 5", location: "Home" },
      { opponent: "vs Giants", date: "Apr 7", location: "Home" },
    ],
  },
];

export const watchlist: WatchlistItem[] = [
  { id: "watch-1", gameId: "nba-bos-den", note: "Track Gordon status before locking final projection.", savedAt: "Today, 10:42 AM" },
  { id: "watch-2", gameId: "mlb-nyy-lad", note: "Monitor Yankees lineup card and total movement around first pitch.", savedAt: "Today, 11:16 AM" },
];

export const dataHealth: DataHealthStatus[] = [
  { provider: "Schedule Provider", status: "Healthy", lastUpdated: "2026-04-04 2:11 PM PT", recordsToday: 26, notes: "Daily slate synced successfully." },
  { provider: "Odds Provider", status: "Healthy", lastUpdated: "2026-04-04 2:14 PM PT", recordsToday: 412, notes: "Three books active; 4-minute refresh cadence." },
  { provider: "Stats Provider", status: "Delayed", lastUpdated: "2026-04-04 1:52 PM PT", recordsToday: 128, notes: "MLB bullpen usage endpoint lagging by one cycle." },
  { provider: "Injury Provider", status: "Warning", lastUpdated: "2026-04-04 12:58 PM PT", recordsToday: 41, notes: "Two player statuses require manual confirmation." },
];
